export const dateFormats = {
  displayFull: 'HH:mm:ss DD/MM/YYYY',
  display0: 'MMM DD,YYYY',
  display1: 'DD.MMM.YYYY',
  display2: 'DD.MM.YY',
  display3: 'DD MMMM YYYY',
  display4: 'DD MMMM',
  display5: 'DD MMM',
  display6: 'DD/MM/YYYY',
  timeDisplay0: 'HH:mm',
  timeDisplay1: 'h:mm A',
  api: 'YYYY-MM-DD',
  userFriendly: 'MMMM D, YYYY',
  iso8601: 'YYYY-MM-DDTHH:mm:ss',
  iso8601Z: 'YYYY-MM-DDTHH:mm:ssZ',
  apiZ: 'YYYY-MM-DDTHH:mm:ss.SSSSSS[Z]',
  minutes: 'MM',
  hours: 'HH',
  weekday: 'dddd',
  day: 'ddd',
  day1: 'DD',
}
